[build]
  command = "pip install -r requirements.txt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "gunicorn wsgi:app --bind=0.0.0.0:$PORT --log-file=-"