services:
    - type: web
      name: attendance-app
      env: python
      buildCommand: pip install -r requirements.txt
      startCommand: .venv/bin/gunicorn wsgi:app --bind=0.0.0.0:$PORT --log-file=-
      envVars:
        - key: PYTHON_VERSION
          value: "3.11.11"
        - key: PORT
          value: "8000"