services:
    - type: web
      name: attendance-app
      env: python
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
      envVars:
        - key: PYTHON_VERSION
          value: "3.11.11"
        - key: PORT
          value: "8000"